name: Build
on:
  schedule:
    - cron:  '0 3 * * 0'
  push:
    branches:
      - master
    paths:
      - '!.github/**'
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Submodule"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    if: |
     !contains(github.event.head_commit.message, 'ci skip') &&
     (github.event.workflow_run.conclusion == 'success' ||
     github.event_name != 'workflow_run' ) 
     
    runs-on: ubuntu-latest

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Commit message: " ${{ github.event.head_commit.message }}
          echo "Conclusion: " ${{ github.event.workflow_run.conclusion }}
          echo "Event name: "${{ github.event_name }}

      # Prepare source code for incremental build
      - name: Download source artifact last build
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-metaproject
          name: source-artifact
          workflow: buildAndExportArtifact.yml
        continue-on-error: true

      - name: 'Untar source files last build'
        run: |
          mkdir -p "$GITHUB_WORKSPACE"
          if [ -e source_files.tar.xz ]; then
            tar -xf source_files.tar.xz -C /
            rm source_files.tar.xz
          fi

      - name: 'Checkout git'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Prepare last build files for incremental build
      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: ZeraGmbH/zera-metaproject
          name: build-artifact
          workflow: buildAndExportArtifact.yml
        continue-on-error: true

      - name: 'Untar build files'
        run: |
          mkdir -p "$HOME/targetbuild"
          if [ -e build_files.tar.xz ]; then
            tar -xf build_files.tar.xz -C /
            rm build_files.tar.xz
          fi

      - name: Build
        run: |
          cd "$HOME/targetbuild"
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_BUILD_TYPE="Release" \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
           -DfirstBuild=ON
          # compile / install
           make -i -j $(getconf _NPROCESSORS_ONLN)

      # Keep sources for incremental checkout
      - name: Tar sources
        run: |
          time tar -c -I 'xz -T0' -f $HOME/source_files.tar.xz "$GITHUB_WORKSPACE"

      - name: 'Upload source artifact'
        uses: actions/upload-artifact@v3
        with:
          name: source-artifact
          path: /github/home/source_files.tar.xz

      # Keep build files for incremental build
      - name: 'Tar build files'
        run: |
          time tar -c -I 'xz -T0' -f $HOME/build_files.tar.xz "$HOME/targetbuild"

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /github/home/build_files.tar.xz

      # Keep install files for actions of submodules (TODO first tar.xz)
      - name: Upload install artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: buildroot
          path: /github/home/install/
