name: Build
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Submodule","Recreate build caches"]
    branches: [master]
    types: 
      - completed

# This workflow runs build and makes submodules libraries available to link
# against.
#
# What are the trigger events?:
# * Manual
# * Scheduled
# * On finish of workflow 'Update Submodule' which is triggered by submodule's
#   'trigger updates' workflow
#
# Some words on caching:
# * When triggered by 'Update Submodule' sources, build-files and installed
#   files are loaded to increase build times on daily business.
#   To speed up, only install artefacts are generated and saved
# * On other 'workflow_dispatch' (manual start) or 'schedule' no artifacts are
#   downloaded so workflow builds from scratch

jobs:
  build:
    if: |
     (github.event.workflow_run.conclusion == 'success' ||
     github.event_name != 'workflow_run' ) 
     
    runs-on: ubuntu-latest

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Commit message: " ${{ github.event.head_commit.message }}
          echo "Conclusion: " ${{ github.event.workflow_run.conclusion }}
          echo "Event name: "${{ github.event_name }}

      # Prepare source code for incremental build
      - name: Download last source artifact last build
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: recreateBuildCachesMeta.yml
          name: source-cache
          check_artifacts: true
        continue-on-error: true

      - name: 'Untar source files last build'
        run: |
          mkdir -p "$GITHUB_WORKSPACE"
          if [ -e source-cache-files.tar.xz ]; then
            tar -xf source-cache-files.tar.xz -C /
            rm source-cache-files.tar.xz
          else
            echo 'source-cache-files.tar.xz not found'
          fi

      - name: 'Checkout git'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Prepare last build files for incremental build
      - name: Download last build artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: recreateBuildCachesMeta.yml
          name: build-cache
          check_artifacts: true
        continue-on-error: true

      - name: 'Untar build files'
        run: |
          mkdir -p "$HOME/targetbuild"
          if [ -e build-cache-files.tar.xz ]; then
            tar -xf build-cache-files.tar.xz -C /
            rm build-cache-files.tar.xz
          else
            echo 'build-cache-files.tar.xz not found'
          fi

      # Prepare last install files for incremental build
      - name: Download last install artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: recreateBuildCachesMeta.yml
          name: install-cache
          check_artifacts: true
        continue-on-error: true

      - name: 'Untar install files'
        run: |
          if [ -e install-cache-files.tar.xz ]; then
            tar -xf install-cache-files.tar.xz -C /
            rm install-cache-files.tar.xz
          else
            echo 'install-cache-files.tar.xz not found'
          fi

      # Build
      - name: Build
        run: |
          cd "$HOME/targetbuild"
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_BUILD_TYPE="Release" \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
           -DfirstBuild=ON
          # compile / install
           make -i -j $(getconf _NPROCESSORS_ONLN)

      # Keep install files for submodule actions
      - name: Tar install files
        run: |
          tar -c -I 'xz -T0' -f $HOME/install_files.tar.xz "$HOME/install"

      - name: 'Upload install artifact'
        uses: actions/upload-artifact@v3
        with:
          name: install-artifact
          path: /github/home/install_files.tar.xz
          retention-days: 1

