name: Cleanup Artifacts
on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: 'Checkout git'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_BUILD_TYPE="Release" \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
           -DfirstBuild=ON
          # compile / install
           make -i -j $(getconf _NPROCESSORS_ONLN)

      # Keep sources for incremental checkout
      - name: Tar sources
        run: |
          time tar -c -I 'xz -T0' -f $HOME/source_files.tar.xz "$GITHUB_WORKSPACE"

      - name: 'Upload source artifact'
        uses: actions/upload-artifact@v3
        with:
          name: source-artifact
          path: /github/home/source_files.tar.xz

      # Keep build files for incremental build
      - name: 'Tar build files'
        run: |
          time tar -c -I 'xz -T0' -f $HOME/build_files.tar.xz "$HOME/targetbuild"

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /github/home/build_files.tar.xz

      # Keep install files for incremental build / submodule actions
      - name: 'Tar install files'
        run: |
          time tar -c -I 'xz -T0' -f $HOME/install_files.tar.xz "$HOME/install"

      - name: 'Upload install artifact'
        uses: actions/upload-artifact@v3
        with:
          name: install-artifact
          path: /github/home/install_files.tar.xz

      # Keep install files for actions of submodules
      - name: Upload install artifact (TODO remove)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: buildroot
          path: /github/home/install/
