name: CodeChecks

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 0'

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang++
          - clazy
        container:
          - schnitzeltony/fedora-qt5:35
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Build
        run: |
          set -x
          mkdir -p build
          cd build

          export CC=clang
          export CXX=${{ matrix.compiler }}

          cmake .. \
            -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
            -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
            -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
            -DfirstBuild=ON
          make -k -j $(getconf _NPROCESSORS_ONLN)

