name: Recreate build caches
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - name: Echo github environment
        run: |
          echo "Home: $HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Commit message: " ${{ github.event.head_commit.message }}
          echo "Conclusion: " ${{ github.event.workflow_run.conclusion }}
          echo "Event name: "${{ github.event_name }}

      - name: 'Checkout git'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Build
      - name: Build
        run: |
          cd "$HOME/targetbuild"
          cmake $GITHUB_WORKSPACE \
           -DCMAKE_BUILD_TYPE="Release" \
           -DCMAKE_PREFIX_PATH="$HOME/install/usr;/usr" \
           -DCMAKE_INSTALL_PREFIX:PATH="$HOME/install/usr" \
           -DCMAKE_INSTALL_SYSCONFDIR="$HOME/install/etc" \
           -DfirstBuild=ON
          # compile / install
           make -i -j $(getconf _NPROCESSORS_ONLN)

      # Keep sources for incremental checkout
      - name: Tar sources
        run: |
          tar -c -I 'xz -T0' -f $HOME/source_files.tar.xz "$GITHUB_WORKSPACE"

      - name: Upload source artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-artifact
          path: /github/home/source_files.tar.xz
          retention-days: 1

      # Keep build files for incremental build
      - name: Tar build files
        run: |
          tar -c -I 'xz -T0' -f $HOME/build_files.tar.xz "$HOME/targetbuild"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: /github/home/build_files.tar.xz
          retention-days: 1

      # Keep install files for incremental build
      - name: Tar install files
        run: |
          tar -c -I 'xz -T0' -f $HOME/install_files.tar.xz "$HOME/install"

      - name: 'Upload install artifact'
        uses: actions/upload-artifact@v3
        with:
          name: install-artifact
          path: /github/home/install_files.tar.xz
          retention-days: 1


