name: Update Submodule
on:
  workflow_dispatch:
    inputs:
      submodule:
        description: submodule name 
        required: false

concurrency: update_submodule

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'ci skip')"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: store commit id before update
        run:  echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Git Sumbodule Update
        run: |
          CI/updateSubmodule.sh ${{ github.event.inputs.submodule}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
      - uses: convictional/trigger-workflow-and-wait@v1.4.0
        with:
          owner: ZeraGmbH
          repo: meta-zera
          github_token: ${{ secrets.G_TRIGGER_WORKFLOW }}
          workflow_file_name: updateRecipes.yml
          inputs: '{"commitid" : "${{ env.COMMIT_ID }}"}'  
          ref: master
